# Generated by Django 5.2.5 on 2026-05-05 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Module name, e.g., 'PLC Programming'", max_length=255)),
                ('tagline', models.CharField(blank=True, help_text='Short tagline for the module.', max_length=500, null=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier, auto-generated from title.', max_length=100, unique=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail image for listing cards.', null=True, upload_to='modules/thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in listing pages.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
                'db_table': 'internships_module',
            },
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('HERO', 'Hero Banner'), ('INTERNSHIP_OPPORTUNITIES', 'Internship Opportunities Section'), ('WHY_CHOOSE_US', 'Why Choose Our Program Section'), ('FEATURE_HIGHLIGHTS', 'Feature Highlights Section'), ('PROGRAM_STRUCTURE', 'Program Structure'), ('FAQ', 'Faq'), ('PAGE_BANNER', 'Page Banner'), ('COURSE_OVERVIEW', 'Course Overview'), ('KEY_HIGHLIGHTS', 'Key Highlights'), ('SUBJECTS_COVERED', 'Subjects Covered'), ('ELIGIBILITY_CRITERIA', 'Eligibility Criteria'), ('FEES_BATCH_DETAILS', 'Fees & Batch Details'), ('FACULTY', 'Faculty'), ('PAST_RESULTS', 'Past Results'), ('TESTIMONIALS', 'Testimonials'), ('CTA', 'Call To Action')], max_length=50),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Link this section to a specific module. Leave blank for standalone internship page sections.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='modules.module'),
        ),
    ]
