# Generated by Django 5.2.5 on 2026-05-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_module_alter_pagesection_section_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='brochure',
            field=models.FileField(blank=True, help_text='Downloadable PDF brochure for the module.', null=True, upload_to='modules/brochures/'),
        ),
        migrations.AddField(
            model_name='module',
            name='syllabus',
            field=models.FileField(blank=True, help_text='Downloadable PDF syllabus for the module.', null=True, upload_to='modules/syllabus/'),
        ),
    ]
