# Generated by Django 5.2.5 on 2026-05-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_module_brochure_module_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='brochure',
            field=models.FileField(blank=True, help_text='Downloadable PDF brochure for this section.', null=True, upload_to='sections/brochures/'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='syllabus',
            field=models.FileField(blank=True, help_text='Downloadable PDF syllabus for this section.', null=True, upload_to='sections/syllabus/'),
        ),
    ]
