# Generated by Django 5.2.5 on 2026-05-15 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_pagesection_brochure_pagesection_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Link this section to a specific module. Leave blank for standalone module page sections.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='modules.module'),
        ),
    ]
