# Generated by Django 5.2.5 on 2026-05-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_alter_pagesection_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('HERO', 'Hero Banner'), ('MODULE_OPPORTUNITIES', 'Module Opportunities Section'), ('WHY_CHOOSE_US', 'Why Choose Our Program Section'), ('FEATURE_HIGHLIGHTS', 'Feature Highlights Section'), ('PROGRAM_STRUCTURE', 'Program Structure'), ('FAQ', 'Faq'), ('PAGE_BANNER', 'Page Banner'), ('COURSE_OVERVIEW', 'Course Overview'), ('KEY_HIGHLIGHTS', 'Key Highlights'), ('SUBJECTS_COVERED', 'Subjects Covered'), ('ELIGIBILITY_CRITERIA', 'Eligibility Criteria'), ('FEES_BATCH_DETAILS', 'Fees & Batch Details'), ('FACULTY', 'Faculty'), ('PAST_RESULTS', 'Past Results'), ('TESTIMONIALS', 'Testimonials'), ('CTA', 'Call To Action')], max_length=50),
        ),
    ]
