# Generated by Django 5.2.5 on 2026-04-21 09:38

from django.db import migrations


def populate_data(apps, schema_editor):
    Announcement = apps.get_model('core', 'Announcement')
    SiteStatistic = apps.get_model('core', 'SiteStatistic')

    Announcement.objects.bulk_create([
        Announcement(icon='🎓', text='Admission Open - Enroll Now for Limited Seats!', order=1),
        Announcement(icon='🚀', text='New Batch Starting - Don\'t Miss Out!', order=2),
        Announcement(icon='💼', text='100% Placement Assistance Available', order=3),
    ])

    SiteStatistic.objects.bulk_create([
        SiteStatistic(icon='⭐', label='Rated', value='4.8/5', sub_label='by 2,000+ students', order=1),
        SiteStatistic(icon='🎓', label='students trained', value='10,000+', order=2),
        SiteStatistic(icon='🏢', label='Placed in', value='top companies', order=3),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_announcement_sitestatistic'),
    ]

    operations = [
        migrations.RunPython(populate_data),
    ]
