# Generated by Django 5.2.5 on 2026-05-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_populate_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Google Maps Embed URL', max_length=500, null=True),
        ),
    ]
