# Generated by Django 5.2.5 on 2026-04-17 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('BANNER', 'Banner'), ('TECH_GRID_1', 'Technology Grid 1'), ('TECH_GRID_2', 'Technology Grid 2'), ('PROCESS_STEPS', 'Development Process'), ('WHAT_WE_PROVIDE', 'What We Provide'), ('WHY_CHOOSE_OUR_SERVICES', 'Why Choose Our Services'), ('GET_IN_TOUCH', 'Get In Touch'), ('CTA', 'Call To Action (Dark)')], max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('super_heading', models.CharField(blank=True, help_text="For BANNER: The small text above the main heading, e.g., 'Premium Development Services'", max_length=200, null=True)),
                ('heading', models.CharField(blank=True, help_text='The main title of the section.', max_length=255, null=True)),
                ('highlighted_heading_text', models.CharField(blank=True, help_text="For BANNER: The part of the heading to be highlighted, e.g., 'Digital Vision'", max_length=100, null=True)),
                ('subheading', models.TextField(blank=True, help_text='The descriptive text under the main heading.', null=True)),
                ('primary_image', models.ImageField(blank=True, help_text='For BANNER: The main image on the right.', null=True, upload_to='sections/')),
                ('background_image', models.ImageField(blank=True, help_text='For CTA: The dark background image.', null=True, upload_to='sections/backgrounds/')),
                ('primary_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_button_url', models.CharField(blank=True, max_length=200, null=True)),
                ('secondary_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_button_url', models.CharField(blank=True, max_length=200, null=True)),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_sections', to='core.submenu')),
            ],
            options={
                'verbose_name': 'Service Page Section',
                'verbose_name_plural': 'Page sections',
                'ordering': ['submenu', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FLOATING_CARD', 'Floating Card'), ('STAT_BAR', 'Stat Bar Item')], default='STAT_BAR', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.ImageField(blank=True, help_text='Icon for Tech Item or Process Step.', null=True, upload_to='icons/')),
                ('title', models.CharField(blank=True, help_text="Main text/title, e.g., 'React.js', 'Discovery', '500+'", max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Descriptive text for the item.', null=True)),
                ('tags', models.TextField(blank=True, help_text="For TECH_ITEM: Comma-separated tags, e.g., 'SSR/SSG, API Routes, Performance'", null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='services.pagesection')),
            ],
            options={
                'verbose_name': 'Section Content Item',
                'verbose_name_plural': 'Section Content',
                'ordering': ['section', 'order'],
            },
        ),
    ]
