# Generated by Django 5.2.5 on 2026-04-17 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('HERO', 'Hero Section'), ('WHO_WE_ARE', 'Who We Are'), ('VISION_MISSION', 'Vision and Mission'), ('GALLERY', 'Gallery'), ('EXPERTISE', 'Expertise'), ('OUR_TEAM', 'Our Team')], max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('super_heading', models.CharField(blank=True, max_length=200, null=True)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('subheading', models.TextField(blank=True, null=True)),
                ('overview_text', models.CharField(blank=True, max_length=255, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='sections/')),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='sections/')),
                ('primary_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_button_url', models.CharField(blank=True, max_length=200, null=True)),
                ('secondary_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_button_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('primary_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_button_url', models.CharField(blank=True, max_length=200, null=True)),
                ('secondary_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_button_url', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='section_content/')),
                ('person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('person_role', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='aboutus.pagesection')),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
    ]
