# Generated by Django 5.2.5 on 2026-05-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('HERO', 'Hero Section'), ('WHO_WE_ARE', 'Who We Are'), ('DIRECTOR_MESSAGE', 'Director / Founder Message'), ('OUR_STORY', 'Our Story'), ('VISION_MISSION', 'Vision and Mission'), ('EXPERTISE', 'Expertise'), ('ACCREDITATIONS', 'Accreditations & Affiliations'), ('INFRASTRUCTURE', 'Infrastructure Highlights'), ('GALLERY', 'Gallery'), ('OUR_TEAM', 'Our Team')], max_length=50),
        ),
    ]
