# Generated by Django 5.2.5 on 2026-04-17 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('section_type', models.CharField(choices=[('HERO', 'Hero Banner'), ('OVERVIEW', 'Overview'), ('WHY_CHOOSE_US', 'Why Choose Us'), ('OUR_SERVICES', 'Our Services'), ('KEY_ACHIVEMENTS', 'Key Achivements'), ('TESTIMONIALS', 'Testimonials Slider'), ('FAQ', 'Frequently Asked Questions'), ('CONTACT_US', 'Contact Us'), ('CTA', 'Call To Action')], max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('super_heading', models.CharField(blank=True, max_length=200, null=True)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('subheading', models.TextField(blank=True, null=True)),
                ('overview_text', models.CharField(blank=True, max_length=100, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='sections/')),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='sections/')),
                ('primary_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_button_url', models.CharField(blank=True, max_length=200, null=True)),
                ('secondary_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_button_url', models.CharField(blank=True, max_length=200, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='homepage.pagesection')),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
    ]
