# Generated by Django 5.2.5 on 2026-04-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('HERO', 'Hero Banner'), ('OVERVIEW', 'Overview'), ('WHY_CHOOSE_US', 'Why Choose Us'), ('OUR_SERVICES', 'Our Services'), ('OUR_PLACED_STUDENTS', 'Our Placed Students'), ('TESTIMONIALS', 'Testimonials Slider'), ('FAQ', 'Frequently Asked Questions'), ('CONTACT_US', 'Contact Us'), ('CTA', 'Call To Action')], max_length=50),
        ),
    ]
