# Generated by Django 5.2.5 on 2026-04-22 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('homepage', '0002_alter_pagesection_section_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesection',
            name='subheading',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='primary_button_url',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='primary_button_text',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='super_heading',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='secondary_button_text',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='secondary_button_url',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='primary_image',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='overview_text',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='section_type',
        ),
        migrations.AddField(
            model_name='pagesection',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='label',
            field=models.CharField(blank=True, help_text='Internal label for this section', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ContactUsSection',
            fields=[
                ('pagesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.pagesection')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('homepage.pagesection',),
        ),
        migrations.CreateModel(
            name='FaqSection',
            fields=[
                ('pagesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.pagesection')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('homepage.pagesection',),
        ),
        migrations.CreateModel(
            name='OurServicesSection',
            fields=[
                ('pagesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.pagesection')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('homepage.pagesection',),
        ),
        migrations.CreateModel(
            name='PlacementSection',
            fields=[
                ('pagesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.pagesection')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('homepage.pagesection',),
        ),
        migrations.CreateModel(
            name='TestimonialSection',
            fields=[
                ('pagesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.pagesection')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('homepage.pagesection',),
        ),
        migrations.CreateModel(
            name='WhyChooseUsSection',
            fields=[
                ('pagesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.pagesection')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('homepage.pagesection',),
        ),
        migrations.CreateModel(
            name='CtaSection',
            fields=[
                ('pagesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.pagesection')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.TextField(blank=True, null=True)),
                ('primary_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_button_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('homepage.pagesection',),
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('pagesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.pagesection')),
                ('super_heading', models.CharField(blank=True, max_length=200, null=True)),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.TextField(blank=True, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='sections/hero/')),
                ('primary_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_button_url', models.CharField(blank=True, max_length=200, null=True)),
                ('secondary_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_button_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('homepage.pagesection',),
        ),
        migrations.CreateModel(
            name='OverviewSection',
            fields=[
                ('pagesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.pagesection')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.TextField(blank=True, null=True)),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='sections/overview/')),
                ('overview_text', models.CharField(blank=True, help_text='Small text above/below image', max_length=100, null=True)),
                ('primary_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_button_url', models.CharField(blank=True, max_length=200, null=True)),
                ('secondary_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_button_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('homepage.pagesection',),
        ),
    ]
