# Generated by Django 5.2.5 on 2026-04-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_pagesection_subheading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='overview_text',
            field=models.CharField(blank=True, help_text='Extra text for additional details or small labels.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ctasection',
            name='heading',
            field=models.CharField(help_text='High-impact title for the Call to Action.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ctasection',
            name='subheading',
            field=models.TextField(blank=True, help_text='Persuasive sub-text for the CTA.', null=True),
        ),
        migrations.AlterField(
            model_name='faqsection',
            name='heading',
            field=models.CharField(help_text='Title for the FAQ accordion.', max_length=255),
        ),
        migrations.AlterField(
            model_name='faqsection',
            name='subheading',
            field=models.TextField(blank=True, help_text='Intro for the questions.', null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='The large full-width image behind the text.', null=True, upload_to='sections/hero/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='heading',
            field=models.CharField(help_text='The big main headline for the banner.', max_length=255),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subheading',
            field=models.TextField(blank=True, help_text='Small description text below the main headline.', null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='super_heading',
            field=models.CharField(blank=True, help_text="Small 'eyebrow' text above the main banner title.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ourservicessection',
            name='heading',
            field=models.CharField(help_text='Main title for the services grid.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ourservicessection',
            name='subheading',
            field=models.TextField(blank=True, help_text='Brief intro text for services.', null=True),
        ),
        migrations.AlterField(
            model_name='overviewsection',
            name='heading',
            field=models.CharField(help_text='Heading for the Overview/About section.', max_length=255),
        ),
        migrations.AlterField(
            model_name='overviewsection',
            name='overview_text',
            field=models.CharField(blank=True, help_text="Tag/Badge text displayed near the image (e.g. '20+ Years Exp').", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='overviewsection',
            name='primary_image',
            field=models.ImageField(blank=True, help_text='The main image shown next to the text.', null=True, upload_to='sections/overview/'),
        ),
        migrations.AlterField(
            model_name='overviewsection',
            name='subheading',
            field=models.TextField(blank=True, help_text="Detailed description or 'About' text.", null=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck this to hide the entire section from the website.'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='label',
            field=models.CharField(blank=True, help_text="Internal label (e.g. 'Main Hero' or 'Why Us Row 1'). Not shown on website.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Control the sequence of sections on the page. Lower numbers appear first.'),
        ),
        migrations.AlterField(
            model_name='placementsection',
            name='heading',
            field=models.CharField(help_text='Title for the placed students slider.', max_length=255),
        ),
        migrations.AlterField(
            model_name='placementsection',
            name='subheading',
            field=models.TextField(blank=True, help_text='Subtitle for placement success.', null=True),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='answer',
            field=models.TextField(blank=True, help_text='The answer (FAQ only).', null=True),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='description',
            field=models.TextField(blank=True, help_text='Body text for the item/card.', null=True),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='icon',
            field=models.ImageField(blank=True, help_text='SVG/Icon image for this item.', null=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='label',
            field=models.CharField(blank=True, help_text='Optional internal label.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls item position.'),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='question',
            field=models.CharField(blank=True, help_text='The question (FAQ only).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='text',
            field=models.CharField(blank=True, help_text='Extra small text or caption.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='title',
            field=models.CharField(blank=True, help_text='Main text for this item (e.g. Service Name).', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testimonialsection',
            name='heading',
            field=models.CharField(help_text='Main headline for student reviews.', max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonialsection',
            name='subheading',
            field=models.TextField(blank=True, help_text='Secondary text for reviews.', null=True),
        ),
        migrations.AlterField(
            model_name='whychooseussection',
            name='heading',
            field=models.CharField(help_text="Header for the 'Why Choose Us' grid.", max_length=255),
        ),
        migrations.AlterField(
            model_name='whychooseussection',
            name='subheading',
            field=models.TextField(blank=True, help_text='Intro text for the cards below.', null=True),
        ),
    ]
