# Generated by Django 5.2.5 on 2026-04-17 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('HERO_CORPORATE', 'Hero Banner (Corporate)'), ('ABOUT_CORPORATE', 'About Section (Corporate)'), ('TRAINING_OFFERINGS', 'Training Offerings Section (Corporate)'), ('WHY_CHOOSE_US', 'Why Choose Us Section (Corporate)'), ('INDUSTRIES_SERVED', 'Industries Served Section (Corporate)'), ('TRAINING_PROCESS', 'Training Process Section (Corporate)'), ('HERO_STUDENT', 'Hero Banner (Student)'), ('TRAINING_OFFERINGS_STUDENT', 'Training Offerings Section (Student)'), ('HIGHLIGHTS', 'Highlights (Student)'), ('PROGRAM_STRUCTURE', 'Program Structure (Student)'), ('WHAT_YOU_WILL_LEARN', 'What You Will Learn (Student)'), ('UPCOMING_BATCHES', 'Upcoming Batches (Student)'), ('OUR_TRAINERS', 'Our Trainers Section'), ('FAQ', 'Frequently Asked Questions')], max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('super_heading', models.CharField(blank=True, help_text="e.g., 'About Our'", max_length=200, null=True)),
                ('heading', models.CharField(blank=True, help_text='The main heading of the section.', max_length=255, null=True)),
                ('highlighted_heading', models.CharField(blank=True, help_text='The part of the heading to be highlighted.', max_length=255, null=True)),
                ('subheading', models.TextField(blank=True, null=True)),
                ('order_level', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='sections/')),
                ('primary_image', models.ImageField(blank=True, help_text="e.g., the photo in the 'About' section", null=True, upload_to='sections/')),
                ('overlay_title', models.CharField(blank=True, max_length=200, null=True)),
                ('overlay_description', models.TextField(blank=True, null=True)),
                ('primary_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_button_url', models.CharField(blank=True, max_length=200, null=True)),
                ('secondary_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_button_url', models.CharField(blank=True, max_length=200, null=True)),
                ('submenu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_sections', to='core.submenu')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('label', models.CharField(blank=True, help_text="e.g., the number '1' for a process step, or '500+' for a metric.", max_length=100, null=True)),
                ('title', models.CharField(blank=True, help_text='The title of the card or item.', max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('brochures', models.FileField(blank=True, null=True, upload_to='brochures/')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags, e.g., Digital Skills,Data Analytics', max_length=255, null=True)),
                ('primary_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_button_url', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=200, null=True)),
                ('other_social_url', models.CharField(blank=True, help_text='For Dribbble, Medium, etc.', max_length=200, null=True)),
                ('question', models.CharField(blank=True, help_text='Add Question for Faq', max_length=500, null=True)),
                ('answer', models.CharField(blank=True, help_text='Add Answer for Faq', max_length=500, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='training.pagesection')),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
    ]
